---
site_name: ESF Engineering Playbook
site_url: https://esf.github.io/engineering-playbook
site_description: ESF Engineering Playbook
site_author: ESF

repo_url: https://github.com/esf/engineering-playbook/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
  palette:
    primary: red 
    accent: red
  logo: resources/esf_icon_white.svg
  favicon: resources/esf_icon_red.svg
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  # - mkdocs-simple-hooks:
  #    enabled: !ENV [ENABLE_MKDOCS_ASPX, False]
  #    hooks:
  #      on_files: "hooks:on_files"

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist
