---
site_name: ESF Engineering Playbook
site_url: https://esf.github.io/engineering-playbook
site_description: ESF Engineering Playbook
site_author: ESF

repo_url: https://github.com/esf/engineering-playbook/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
  palette:
    primary: red 
    accent: red
  logo: resources/esf_icon_white.svg
  favicon: resources/esf_icon_red.svg
  features:
    - navigation.instant
    - navigation.indexes

nav:
  - About this Playbook: README.md
  - About ESF Engineering: ESF-engineering.md
  - Engineering Fundamentals Checklist: engineering-fundamentals-checklist.md
  - Week One of a Project: week-one-of-a-project.md
  - Agile & Ceremonies: agile-development/ceremonies.md
  - Working Agreement: agile-development/team-agreements/working-agreement.md
  - Pull Requests & Code Reviews: code-reviews/pull-requests.md
  - Source Control: source-control/README.md
  - CI/CD: CI-CD/continuous-integration.md
  - Secrets Management: CI-CD/dev-sec-ops/secrets-management/README.md
  - Testing: automated-testing/README.md
  - Design & NFRs: design/design-patterns/non-functional-requirements-capture-guide.md
  - Security: security/README.md
  - Observability: observability/best-practices.md
  - Privacy: non-functional-requirements/privacy/privacy-frameworks.md
  - Developer Experience & AI Tools: developer-experience/copilots.md
  - Responsible AI: ml-and-ai-projects/responsible-ai.md
  - ML Fundamentals Checklist: ml-and-ai-projects/ml-fundamentals-checklist.md

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  # - mkdocs-simple-hooks:
  #    enabled: !ENV [ENABLE_MKDOCS_ASPX, False]
  #    hooks:
  #      on_files: "hooks:on_files"

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist
